### PR TITLE
CSM 12 add moldable plastics as material

### PR DESCRIPTION
**Pull request by woodbe**
CSM 12: Suggest to add in Moldable Plastic for M.4.

Proposal: Instruction to create fingerprint mold from moldable plastic is general. E.g. https://pollyplastics.com/pages/moldable-plastic-instructions

From spreadsheet

### CODE REVIEW

**Comment by woodbe** [comment]
I'm not certain about this (or about the requirements on the plastics itself). One thing though is that my intent in this review cycle is to combine the test cases into a smaller number with variants, which would mean this would just get rolled into a variant, so not a lot of extra work (though it would seem to need instructions in the overview).

I'm also not sure if we specifically care about this compared to the dental impression material, whether it provides enough differentiation in the results to want to add it or not.

**Comment by n-kai** [comment]
As described in "6.2.1. Independent test activities using Toolbox" in SD, evaluator shall create and test all PAIs defined in the toolbox for ATE_IND.1 to keep consistencies among different evaluations.  But, as described in "7.1.1. Artefact production" in "Biometric PAD Toolbox Overview" the evaluator can modify the production process of PAI (including change of materials) but such changes that has proved effective through actual testing should be reported to the BIO iTC so that we can update the toolboxes with confidence (and add new variant as you suggest).

I think that we should explain this process to CSM, rather than adding moldable plastic material to inventory now.

**Comment by woodbe** [comment]
I have no issue with that, I just put it in to start (since we are still early on).

I would expect the tests themselves would be the same, so it would mainly be a matter of having the proper instructions for setting it up and making sure what the parameters are for the plastics so the right ones are used.

I will reach out to them on this.

**Comment by woodbe** [comment]
This is on hold awaiting a response from Cybersecurity Malaysia as to the timing for being able to provide the needed information to fully add this.

**Review by n-kai — CHANGES_REQUESTED** [review]
I added the same comment to your commit but repeated here so that every can see my comment more easily
 
Instruction below is for PCB mold and should be changed
**==== Configuration of Mold Tools and Materials
The copper cladding thickness can be varied to produce differing height ridges in the casts.**

**Comment by woodbe** [comment]
Closing this as it is superseded by #73

**Pull request closed without merging**
