### PR TITLE
CSM 5 image -> topology

### PR DESCRIPTION
**Pull request by woodbe**
CSM 5: and extract topology information from the image data - Which fingerprint topology been referred? Is it contact or contactless or the data retrieve from the fingerprint?

Proposal: Does this refer to the contact, contactless or fingerprint data from fingerprint scannning ?

From spreadsheet

### CODE REVIEW

**Comment by woodbe** [comment]
I'm not sure if this text is really good or if a somewhat more major rewrite of the section would be better. The point I'm trying to make with the edit is that the method of capture doesn't really matter as long as the tester is able to extract the needed ridge/valley data.

**Review by n-kai — COMMENTED** [review]
I think that the following two text is introduction to the later section. 

_The simplest is to create a mold directly from the finger. The mold material should be soft enough to not alter the shape of the finger._ -> Intro to 2.2.1.1.1.

_Another way is to image the finger and extract topology information from the image data. This topology data can be used to produce a mold containing friction ridges._ -> Intro to 2.2.1.1.2.

So it should be changed as follows (but need confirmation from @gregott)

The simplest is to create a mold directly from the finger. The mold material should be soft enough to not alter the shape of the finger, **as explained in 2.2.1.1.1** . Another way is to image the finger and extract topology information from the image data. This topology data can be used to produce a mold containing friction ridges, **as explained in 2.2.1.1.2**.

**Comment by gfiumara** [comment]
Agree with @n-kai. In 2.2.1.1.2, we should also add the word "topology." Maybe "Acquiring friction ridge **topology** data"

**Comment by woodbe** [comment]
I have updated this change to shorten the initial intro paragraph and move some of the following sentences into the next sections. I think that this makes is more clear (and I added the topology), but not duplicating things as well.

**Review by gfiumara — APPROVED** [review]

**Review by n-kai — APPROVED** [review]

**Comment by woodbe** [comment]
@woodbe will merge this after the call (resolve conflicts)

**Pull request merged**
