### PR TITLE
3D combined attack proposal

### PR DESCRIPTION
**Pull request by woodbe**
This is the combined attack proposal for all 3 variants into a single document.

The 2D only version is #68.

### CODE REVIEW

**Comment by gfiumara** [comment]
Can we also remove the duplicate tables and mention the attack potentials are identical for all variants?

**Comment by woodbe** [comment]
@gfiumara we could remove the tables if they are all the same. I left individual tables for each variant as that is what we followed in the other toolboxes (where they are usually, but not always, the same).

I don't have a problem marking things as "these are all the same" or "these two are the same, this other one is different and here are the tables for it". 

I have posted an update for this one that has it noted that all values are the same in this attack series.

**Comment by woodbe** [comment]
@woodbe will complete the remaining attacks to match this for review

**Review by n-kai — CHANGES_REQUESTED** [review]
In 03-xx-Fingerprint_attack.adoc, the following text should be changed.

Configuration of Mold Tools and Materials
The copper cladding thickness can be varied to produce differing height ridges in the casts.
->
Different dental impression materials can be used.

**Review by n-kai — COMMENTED** [review]
**The copper cladding thickness can be varied to produce differing height ridges in the casts**
This text comes from L57 in original attacks. See attack 02-01 (https://github.com/biometricITC/Fingerprint-Toolbox/blob/master/attacks/02-01-Fingerprint_attack.adoc)

**Different dental impression materials can be used.**
This text also come from L59 in original attacks. See attack 03-01 (https://github.com/biometricITC/Fingerprint-Toolbox/edit/master/attacks/03-01-Fingerprint_attack.adoc)

So **Different dental impression materials can be used.** should not be removed because it was reviewed and agreed during the public review. (but I can change my mind if the other members agree to delete it)

**Comment by woodbe** [comment]
@n-kai I removed that removal (I was looking at how I brought the files over and clearly missed the history of that statement).

Should we look to add similar statements for all the attacks then (like using different transparency or printers for attack 1)?

**Review by n-kai — APPROVED** [review]
_Should we look to add similar statements for all the attacks then (like using different transparency or printers for attack 1)?_
I don't think so because original attack doesn't include such statement.

**Comment by gregott** [comment]
I am OK with adding or not adding the variation of using different laser printers.  However, different transparency materials should not make any difference to the testing.

**Review by gfiumara — APPROVED** [review]

**Review by gregott — CHANGES_REQUESTED** [review]
For all variations of Gelatin/glycerin mix cast, the material T.5 Water filter is not needed.  It is used when preparing the cast material, not when forming a cast in the mold.

**Comment by woodbe** [comment]
> For all variations of Gelatin/glycerin mix cast, the material T.5 Water filter is not needed. It is used when preparing the cast material, not when forming a cast in the mold.

@gregott I'm confused by this statement since those instructions are for the cast, and the cast needs to use filtered water. The instructions for using it are actually in the inventory, this is just listing out what is needed.

So are you expecting to remove the T.5 from the list? It is in the original docs you sent over.

**Comment by gregott** [comment]
@woodbe The cast material, aka "gelatin / glycerin mix" contains gelatin, glycerin and water.  Here we list "the mix" _and_ water.  The water is already in the mix, so why list it here again when we do not also list glycerin and gelatin again?

**Comment by woodbe** [comment]
@gregott Technically we aren't saying water, we are stating the water filter as a tool that is needed. T are the tools needed, C are the cast materials. I won't dispute that C in this case has water, but from an inventory standpoint, you needed the T.5 filter to create the C.3 cast materials.

I have been just listing the complete inventory of what is needed for each attack for completeness. This is the first time we have tried putting in all the instructions in the inventory, so maybe we need to rethink how we want to do it if there is a better way.

**Comment by woodbe** [comment]
@woodbe will do the following:

- edit the attacks to only show the tools needed to create the cast, not the tools needed to create the cast material
- in the overview, add some paragraphs about how to use the attack & inventory documents (what is created where)
- fix the inventory doc (missing tools for glycerin)

**Review by woodbe — COMMENTED** [review]
@gregott should have the needed changes included now

**Comment by woodbe** [comment]
I added the verification list of all the attacks to this update as well to close #8 once this is approved.

**Review by gregott — APPROVED** [review]

**Comment by gregott** [comment]
@woodbe I approved the update but had a grammatical typo that needed fixed.  Not knowing if that would undo the previous approvals, I am adding this note so you can do your editing magic.

In each of the attacks, the Input section states "The fingers of **a** cooperative subjects for use in capturing images of the subjects’ friction ridge patterns. "  This should be "The fingers of cooperative subjects ..."

**Comment by woodbe** [comment]
> @woodbe I approved the update but had a grammatical typo that needed fixed. Not knowing if that would undo the previous approvals, I am adding this note so you can do your editing magic.
> 
> In each of the attacks, the Input section states "The fingers of **a** cooperative subjects for use in capturing images of the subjects’ friction ridge patterns. " This should be "The fingers of cooperative subjects ..."

@gregott Just fixed. Good catch

**Review by n-kai — APPROVED** [review]

**Review by gfiumara — APPROVED** [review]

**Pull request merged**
