### PR TITLE
additional tool is not needed

### LINKED ISSUE #82: Attack Fingerprint 04-xx no instructions for T.5 Water Filter
Attack 04-xx lists T.5 Water filter in the section Common Attack Tools and Mold Materials. However, none of the recipes make use of the water filter.

### PR DESCRIPTION
**Pull request by woodbe**
this is to close #82

### CODE REVIEW

**Comment by gfiumara** [comment]
C.3 Gelatin with Glycerin Instructions, which is referenced by 04-xx, says to use a filter.

**Comment by woodbe** [comment]
So this one is a little tricky, I think. The instructions here are about the molds, and the molds don't use filtered water. I agree that the species do (C.2 does as well), but we wrote these to sort of assume you have created the stuff you will use to create the species already, so I'm not sure we need to have those dependencies listed here if they are only used there.

I can really go either way, but that is how I read this and why I created the pull request.

**Comment by gregott** [comment]
The Attacks are organized by mold type and then within each attack for a give mold type, the variations of the cast materials are described.  The materials listed in the section titled "Common Attack Tools and Mold Materials" pertain to the mold, not the casts.  Materials needed for the casts should be implied by reference to cast materials used in the Variations section, i.e. C.2 and C.3.  I agree that filtered water does not belong here.

**Comment by woodbe** [comment]
Merged based on call

**Pull request merged**
