### PR TITLE
FBI spec reference

### LINKED ISSUE #81: T.1 Dead link to FBI EBTS Appendix F scanners
The link to [FBI EBTS Appendix F scanners](https://www.fbibiospecs.cjis.gov/certifications) in T.1 no longer works.

Suggest updating the link to:
https://fbibiospecs.fbi.gov/certifications-1/cpl

### PR DESCRIPTION
**Pull request by woodbe**
This is to close #81

### CODE REVIEW

**Comment by gfiumara** [comment]
Conditionally approve. The link previously went to the EBTS standard, where Appendix F (the scanner testing procedure) is defined. This new link goes to the Certified Products List, which is the list of scanners that have gone through and passed the testing defined in Appendix F. Slightly different. In this case, we're saying we want to use a certified scanner, so might be better to update the text to say that.

**Comment by woodbe** [comment]
The link I put in is different than the one suggested in the Issue, that one takes you to the page where you can download the latest version of the specs, not the CPL. I should have mentioned that in the submission, but I did find the proper link, but instead of going to a specific version I linked to the page with the approved version of the spec (more like the NIST pages for a spec instead of directly to the PDF or something ).

**Comment by gfiumara** [comment]
Oops, my mistake. Yes, I was looking at the issue.

**Review by gfiumara — APPROVED** [review]

**Comment by gregott** [comment]
The link in the Requirements Column is fine.  The link in the Commercial Examples column is still broken.  Should it be a link to the certified scanner list? Items in this column are only meant to be examples so pointing the certified scanners list should not be a problem.

**Comment by woodbe** [comment]
I have updated that link as well. It goes to the updated product certifications page.

**Pull request merged**
